### ISSUE TITLE
Individual model loaded for each client

### ISSUE THREAD

**Issue by Khreas** [collabora/WhisperLive#109]
First of all, thanks for the great project!

I've been playing around with the codebase recently and managed to deploy a server on a cloud instance quite easily thanks to the Docker images provided. However, it seems that a new model is loaded in memory for each websocket being opened, making GPU deployment hard to scale to 10+ clients on relatively small GPUs (8Go).

My understanding that a new model is loaded for each websocket opened comes form these code bits and the output of `nvidia-smi` for different number of clients connected:

https://github.com/collabora/WhisperLive/blob/0942dc2cfd8ba9fc0f21ecb623b73136526fb092/whisper_live/server.py#L252-L257

https://github.com/collabora/WhisperLive/blob/0942dc2cfd8ba9fc0f21ecb623b73136526fb092/whisper_live/transcriber.py#L132-L139

Am I correct that an invididual model is loaded for each client, even if two clients have the same model flavor?

If so, is that a design choice that was made or something that has been left for later? I'd be happy to work on a PR for that if such an addition was planned.

**Comment by makaveli10** [comment]
@Khreas thanks for using WhisperLive.
I think that was the simplest solution at that moment. We have planned this in a future release already but haven't yet started development around that. If you'd like to open a PR by re-using an already instantiated model of the same size feel free to do so. 
Things that you might want to keep in mind the `ServeClient` class which instantiates the model associates itself with a `client_id`. Which is used to add the received audio-buffers to the right `ServeClient` object so, we will have to redesign the server a little bit if we want to re-use WhisperModel of the same size.

**Comment by Khreas** [comment]
Thanks for the clarification and the advices @makaveli10! I'll start looking at it next week.
