### ISSUE TITLE
WARNING:root:cannot import WhisperTRTLLM

### ISSUE THREAD

**Issue by kbondnewera** [collabora/WhisperLive#111]
when i am run server i am getting this error
WARNING:root:cannot import WhisperTRTLLM

**Comment by makaveli10** [comment]
@kbondnewera thanks for using WhisperLive, that is a debug log in case someone is using TensorRT-LLM backend and not able to import the `WhisperTRTLLM` transcriber which should fail if TensorRT-LLM related packages are not installed and WhisperLive should revert to `faster-whisper`. That said, we will remove this log in a future update.
