### ISSUE TITLE
Hallucination problem with custom models

### ISSUE THREAD

**Issue by luizakar2002** [collabora/WhisperLive#113]
First of all, thanks for the project!

I'm using custom tiny whisper on cpu with faster whisper as backend. The problem is that I get lots of garbage transcription. Could you give some solutions or hints on how to modify Whisper Live, even if it's a whisper model problem?

Thanks in advance.

**Comment by makaveli10** [comment]
@luizakar2002 Thanks for using WhisperLive. 
Could you elaborate on garbage transcriptions? If you can share the model or the outputs we will be able to assist you better.

**Comment by luizakar2002** [comment]
Sure, I print the result of transcription in _speech_to_text_ method of _ServeClientFasterWhisper_ after spelling just one word and this is what it gives

RESULT
Թոքերը: ԱՉԱՉԱՅԻՆ ՏՈՄՈԳՐԱՖԻԱ ՆՏՈԳՖԻԱ ՆկՔ ՄՈԳՖԻԱ ՆՏ
RESULT
Թոքերի: Թոքերի: ԱՅԻՈԼՈԳՉԱՅԻՆ Տ-ով:
RESULT
Թոքերի: Թոքերի: ԱՅԻՈԼՈԳՉԱՅԻՆ Տ-ով:
RESULT
Թոքերի: Թոքերի: ԱՅԻՈԼՈԳՉԱՅԻՆ Տ-ով:
RESULT
Թոքերի: Թոքերի: ԱՅԻՈԼՈԳՉԱՅԻՆ Տ-ով:
RESULT
Թոքերի: Թոքերի: ԱՅԻՈԼՈԳՉԱՅԻՆ Տ-ով:

Only the first word of the output is spelled (_Թոքերի_) , the rest is hallucination.
Sorry I can't share the model, I can give some details that it is a tiny whisper fine-tuned on custom Armenian dataset. Also it doesn't hallucinate when a file is transcribed.
In Whisper Live, in _speech_to_text_ method of _ServeClientFasterWhisper_ I've tried to modify this part, changing 1.0 to 3.0 or more
            _if duration<3.0:
                continue_
but it didn't help.
Thanks for your quick reply!

**Comment by makaveli10** [comment]
> Also it doesn't hallucinate when a file is transcribed.

@luizakar2002 you mean it doesnt hallucinate even when a file is transcribed with custom model?

**Comment by luizakar2002** [comment]
> > Also it doesn't hallucinate when a file is transcribed.
> 
> @luizakar2002 you mean it doesnt hallucinate even when a file is transcribed with custom model?

Yes, that's correct.

**Comment by makaveli10** [comment]
Can you try another model with your microphone?
Another thing I would try is to save the received audio chunks and see how they sound.

**Comment by luizakar2002** [comment]
@makaveli10 After lots of testings, I found that it hallucinates only on first audio chunk (or on the first chunk after silence). I haven't figured out the reason yet, so for now I don't send the first one to the client.
Can the VAD filter be the reason? Also, I checked the saved recordings and they're fine in quality.

**Comment by makaveli10** [comment]
Make sure the duration of the audio chunk you send for transcription is not too short. 
Also, I would recommend to log the segments and check the `no_speech_prob` and see if you can filter the segments with high `no_speech_prob`. You can log the segments here:
https://github.com/collabora/WhisperLive/blob/8c36768f7f043e559c32b587ee35df2625c0fc7e/whisper_live/server.py#L777
```
print(s.no_speech_prob)
```
