### ISSUE TITLE
[Bug] Duplicate text while using chrome extension

### ISSUE THREAD

**Issue by lightwastak3n** [collabora/WhisperLive#117]
I've added saving to a file to a chrome extension but there seems to be a bug in the whisper server. Every now and then it returns repeated text.

I'm running this on cpu (Ryzen 2400g) using tiny or base models. Small isn't quite real time for me so I haven't done any testing there. 
I've noticed that sometimes the transcription skips a few seconds right before this happens. Not sure if it's my cpu but using faster whisper directly I get about 0.1 RTF (30 seconds for 5 min of audio) using tiny int8.
Could it just be hallucinations? I haven't encountered any like these while transcribing hours of audio using faster whisper.

This is the unmodified chrome extension from this repo
![whisper_chrome_duplicate2](https://github.com/collabora/WhisperLive/assets/54376354/80d2df95-c309-4c33-a1fb-fcb0f0390332)

This is the modified extension. I've also added the whole output to the transcription div so it's easier to see
![whisper_chrome_duplicate](https://github.com/collabora/WhisperLive/assets/54376354/cdf8c98c-37fc-4e8e-8cf8-33c2321655a7)

**Comment by makaveli10** [comment]
@lightwastak3n Hello, can you check which model are you using? We have seen this behaviour if we use `multilingual` model with `English` so, make sure you use `english-only` model.
By default we use multilingual model, so please change this to `"small.en"`
https://github.com/collabora/WhisperLive/blob/8c36768f7f043e559c32b587ee35df2625c0fc7e/whisper_live/server.py#L556

**Comment by makaveli10** [comment]
You're right there are a few things that changed, we will have to change the extension interface and remove the multilingual option instead give options to use `tiny`, `tiny.en` and so on. Thanks for pointing that out.

Although about the repition, could you log the segments
https://github.com/collabora/WhisperLive/blob/2c8a25d3551ae84ce2052a9757a3424a5a817561/whisper_live/server.py#L772

here and see the `no_speech_prob` in each segment, maybe filtering the segments based on the `no_speech_prob` would help.
