### ISSUE TITLE
KeyError: 'model' for server side

### ISSUE THREAD

**Issue by LeoHsu0802** [collabora/WhisperLive#120]
when I running WhisperLive server on EC2 and try to use local laptop with microphone as below
```
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "XX.XX.XX.XX",
  9090,
  is_multilingual=False,
  lang="hi",
  translate=False,
  model="small"
)
client()
```
I got Type Error at first

`TypeError: TranscriptionClient.__init__() got an unexpected keyword argument 'model'`

after I change parameter as below

```
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "XX.XX.XX.XX",
  9090,
  is_multilingual=False,
  lang="hi",
  translate=False,
  model_size="small"
)
client()
```

I got Key Error from server side

```
INFO:websockets.server:connection open
INFO:root:New client connected
ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/websockets/sync/server.py", line 498, in conn_handler
    handler(connection)
  File "/home/ubuntu/WhisperLive/whisper_live/server.py", line 161, in recv_audio
    model=options["model"],
KeyError: 'model'
```

**Comment by makaveli10** [comment]
Hi, thanks for your interest in WhisperLive. Please check the readme again, we updated the readme to use, `model` instead of `model_size` in the client. The reason is people might want to use custom model so, in that case `model_size` is a bit confusing.

**Comment by LeoHsu0802** [comment]
Hi, try model also but I got error

```
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "XX.XX.XX.XX",
  9090,
  is_multilingual=False,
  lang="hi",
  translate=False,
  model="small"
)
client()
```

`TypeError: TranscriptionClient.__init__() got an unexpected keyword argument 'model'
`

**Comment by LeoHsu0802** [comment]
Oh I see, the PyPI library for WhisperLive still stale and I use it for my client side that's why. Please update for PyPI.

**Comment by makaveli10** [comment]
@LeoHsu0802 we will update the package this week.

**Comment by makaveli10** [comment]
@LeoHsu0802 we published a new release. Please upgrade whisper-live and see if the issue is resolved.

**Comment by LeoHsu0802** [comment]
@makaveli10 thanks, it works now. I wonder know if I can use chinese as lang like 'zh'?
