### ISSUE TITLE
Collecting the final transcription

### ISSUE THREAD

**Issue by Zkarape** [collabora/WhisperLive#122]
Thanks for the work done, first of all!

Could you please assist me in collecting the final transcription? I want to keep the completed parts of the transcription as an output while updating the incomplete part. How can I achieve this?

I noticed that after reaching some threshold (which I cannot find), a segment is considered complete and the server starts working on a new segment. I want to collect the complete ones in a list and always print them before printing the incomplete ones.

Hope this makes sense :)

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/121
