### ISSUE TITLE
CPU at 1800% in idle

### ISSUE THREAD

**Issue by kleag** [collabora/WhisperLive#137]
Hi,
When running the server and the client on my Linux laptop, when there is no sound, all CPU cores are used at 100% (see attached htop screenshot on my 20 cores pc). 

When the server is started and the client connect, the CPU stay around 500%  in plain silent and around the same when I start speeking. A few seconds after the first round of speech, the CPU use rises up to 1900% and stays there. During this time, the following info is continuously (and very quickly) printed. 
```
INFO:faster_whisper:VAD filter removed 00:12.680 of audio
INFO:faster_whisper:Processing audio with duration 00:12.680
```
When speaking again, CPU reaches again a steady 500% and the above messages slow down.

![image](https://github.com/collabora/WhisperLive/assets/3354467/1d2ac197-0379-4c91-a282-1f86b1b1a2bf)

**Comment by kleag** [comment]
Note that if I add a 1 second sleep before the `continue` here:
https://github.com/collabora/WhisperLive/blob/9d29b08cea2fc6224cf3d27cf97fbeef55b137a7/whisper_live/server.py#L727

the CPU oscillates between 150 and 300 % in idle (instead of 1900%) and the performance seems to stay similar on continuous speech. It seems to be still too much cpu though and it does not identify what happens precisely.

**Comment by stkr22** [comment]
Can confirm, had similar issues when running server and client on the same machine.

**Comment by zakack** [comment]
Also had this issue when using server and client on the same machine, but I found that passing `use_vad=False` to `TranscriptionClient` cleared it up.

**Comment by makaveli10** [comment]
@kleag can you update whisperlive and see if the issue still persists. let us know how it goes with the new version

`pip install whisper-live --upgrade`

**Comment by makaveli10** [comment]
Whats the model size that you are using? because for me even with small my results are same for cpu usage with or without `vad`

**Comment by makaveli10** [comment]
@kleag we are looking into this at our end as well. Thanks for waiting on this, we will get back to as soon as this is fixed.

**Comment by makaveli10** [comment]
@kleag Do you mind testing out the PR at your end if it solves the issue? On my machine, the CPU usage is less than 100% now and doesnt fully utilize all the cores.

Thanks again for raising the issue.

**Comment by kleag** [comment]
> @kleag Do you mind testing out the PR at your end if it solves the issue? On my machine, the CPU usage is less than 100% now and doesnt fully utilize all the cores.
> 
> Thanks again for raising the issue.

Yes, it works great! Thanks for your quick action.
As you say it uses now less than 100% of one core in idle and only 500-600% when transcribing. Perfect.
