### ISSUE TITLE
Why is writing frames to disk no optional?

### ISSUE THREAD

**Issue by stkr22** [collabora/WhisperLive#141]
I was wondering why writing the chunks to disk is necessary for the client. I could not really find a reason in the code. If it's optional it might make sense to make it optional for saving the io.

**Comment by makaveli10** [comment]
@stkr22 yes good point, we will make it optional in an upcoming release next week.

**Comment by fallenangel3k** [comment]
thanks!!! this is especially an option if you have only tiny SSDs but much RAM and VRAM
