### ISSUE TITLE
cublas64_12.dll error and docker error with new code

### ISSUE THREAD

**Issue by mkatic007** [collabora/WhisperLive#150]
Local version gives error: ERROR:root:[ERROR]: Failed to transcribe audio chunk: Library cublas64_12.dll is not found or cannot be loaded
Docker version gives this error when installing:
Unable to find image 'ghcr.io/collabora/whisperlive-gpu:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/collabora/whisperlive-gpu/manifests/latest": unauthorized.

The issue was not present on previous attempts of install last week on same machines.

**Comment by makaveli10** [comment]
@mkatic007 docker image is public now, you should be able to pull it without any issues, thanks!
