### ISSUE TITLE
tensorRT whisper is not working on multilingual!! (I'm korean)

### ISSUE THREAD

**Issue by ssifood** [collabora/WhisperLive#155]
anyone is there Who working on TensorRT whisper on multinugal?

i do try multiple on smal/medium/large-v3 model.

but all model is printing on english output.

please help me~!!!@

**server**
root@9a18589c6385:/home/WhisperLive# python3 run_server.py -p 9090 -b tensorrt -trt /root/TensorRT-LLM-examples/whisper/whisper_medium -m 

**# client**
audio_file_path =  "C:/archive1/develop/test_audio/06_01_104204_220818_0003_NV_cut30.wav"
host="172.16.40.220"
port = 9099
lang = "ko"
model ="medium" #"large-v3"

from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  host,
  port,
  lang=lang,
  translate=False,
  model=model,
  use_vad=False,
)

client(audio_file_path)

**Comment by ssifood** [comment]
i think

**we must to this**

```bash
wget --directory-prefix=assets https://raw.githubusercontent.com/openai/whisper/main/whisper/assets/multilingual.tiktoken

tokenizer.py 
vocab_path catch teh that multiliugual.tiktoken!!!!

**Comment by makaveli10** [comment]
@ssifood thanks for pointing this out we are looking into this. we will update here with the fix.
