### ISSUE TITLE
tee same audio input to multiple client tasks

### ISSUE THREAD

**Issue by jsichi** [collabora/WhisperLive#165]
For the application I'm working on, I want to be able to process a single audio input (e.g. microphone) and run multiple client tasks against it; e.g. one is transcribing verbatim, and the other is translating into English simultaneously.

It wasn't difficult to refactor the existing code as follows:

* TranscriptionClient takes a list of Client instances.
* The existing Client methods related to processing the input move to TranscriptionClient
* At a few places, such as send_packet_to_server, iterate over all clients

Then I just created one Client per task, passed them into a single TranscriptionClient, and executed that.

It seems like this might be a common use case, so if there's interest in this, I can clean it up and submit a PR.

**Comment by makaveli10** [comment]
Hello @jsichi, yes that would be great, feel free to open a PR and we can take it from there.
Thanks
