### ISSUE TITLE
Can not install whisper-live 

### ISSUE THREAD

**Issue by hermify** [collabora/WhisperLive#166]
When i try to install whisper-live, i get error:

`**ERROR: Cannot install whisper-live==0.0.1, whisper-live==0.0.2, whisper-live==0.0.3, whisper-live==0.0.4, whisper-live==0.0.5 and whisper-live==0.0.6 because these package versions have conflicting dependencies**
`

<img width="1388" alt="Bildschirmfoto 2024-03-05 um 10 07 53" src="https://github.com/collabora/WhisperLive/assets/22779096/9199f281-c2cf-4afb-9285-3e84070bfc9c">

Someone had the same? 

---
When i try to install whisper-live==0.0.6 :
`
ERROR: Could not find a version that satisfies the requirement faster-whisper==0.6.0 (from whisper-live) (from versions: none)
ERROR: No matching distribution found for faster-whisper==0.6.0
`

**Comment by makaveli10** [comment]
Hello @hermify, i could install version 0.0.6 successfully, maybe you could clear your pip's cache and retry, not sure why you want to install an older version?

**Comment by hermify** [comment]
Ok, i manually installed the requirements 
pip install -r requirements/client.txt 

Works :-)
