### ISSUE TITLE
Client may hang due to race condition if server returns error during connection

### ISSUE THREAD

**Issue by jsichi** [collabora/WhisperLive#176]
I accidentally encountered this running the test_server.TestServerInferenceAccuracy because the subprocess spawning run_server.py was picking up the wrong Python venv, so the server wasn't allowing the client to connect successfully.

The race condition in client.py is as follows:

1) After "Waiting for server ready .." the client goes into a busy loop waiting for the recording flag to become true, aborting if there is any server_error.

2) In on_error, server_error correctly gets set to true.

3) But in on_close, server_error gets reset to false.

So if on_close gets called too fast, before the waiting loop has a chance to see the server_error flag set to true, then the loop will go on forever.

**Comment by makaveli10** [comment]
Thanks for looking into this, I think the `server_error` should be True in `on_close` if its not already True, setting it to `False` in `on_close` doesnt make much sense or does it?

**Comment by jsichi** [comment]
I submitted a PR to just delete the line that clears the flag.  Since clients aren't meant to be reused, this seems like the right fix.
