### ISSUE TITLE
Error on running local version

### ISSUE THREAD

**Issue by mkatic007** [collabora/WhisperLive#179]
D:\WhisperLive-main>python run_server.py --port 9090 --backend faster_whisper
Traceback (most recent call last):
  File "D:\WhisperLive-main\run_server.py", line 2, in <module>
    from whisper_live.server import TranscriptionServer
  File "D:\WhisperLive-main\whisper_live\server.py", line 12, in <module>
    from whisper_live.transcriber import WhisperModel
  File "D:\WhisperLive-main\whisper_live\transcriber.py", line 16, in <module>
    from faster_whisper.audio import decode_audio, pad_or_trim
ImportError: cannot import name 'pad_or_trim' from 'faster_whisper.audio' (C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_whisper\audio.py)

**Comment by makaveli10** [comment]
Hello, upgrade `faster_whisper==1.0.1`

**Comment by mkatic007** [comment]
Hi, how can I do this upgrade? Also which CUDA should I have 11 or 12?

**Comment by mkatic007** [comment]
Thank you, I will pay more attention to the requirements from now on. You are doing fantastic work here!
