### ISSUE TITLE
The server keeps returning 'you'.

### ISSUE THREAD

**Issue by Ye83** [collabora/WhisperLive#182]
"This is the data returned by the server. I have been inputting voice, and the 'text' field has been consistently returning 'you':"
![1710250549702](https://github.com/collabora/WhisperLive/assets/17722346/a003e316-9ce2-41c8-b46b-0fb2316c8c54)

"The server appears to be functioning without any abnormalities."

**Comment by makaveli10** [comment]
@Ye83 Can you somehow check the sample rate of the transmitted audio ? The server expects  audio with sample rate `16000`

**Comment by Ye83** [comment]
My client is in Java and can only transmit data as byte[]. Does the server side only accept float32Array data? What should I do?”

**Comment by Ye83** [comment]
I have already handled it，thank you

**Comment by wilsonlv** [comment]
@Ye83 Hi ! Would you share the code please ?
