### ISSUE TITLE
Output to user define location

### ISSUE THREAD

**Issue by ajeema** [collabora/WhisperLive#183]
I've tried to look through documentation of other issues but have yet to find a clear solution. 

using a very simple test
`from whisper_live.client import TranscriptionClient

client = TranscriptionClient(
    "localhost",
    9090,
    lang="en",
    translate=False,
    model="small",
    use_vad=False
)

client(
    hls_url="http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8")
`

How can I define a location to save the text to?

**Comment by zoq** [comment]
I can see that the srt file location is not exposed to the Transcription client:

https://github.com/collabora/WhisperLive/blob/754f22dfae2ab2319c887a74b28d97824cb6f5ef/whisper_live/client.py#L513-L514

I'll open a PR with the change.
