### ISSUE TITLE
 replace the model on Hugging Face

### ISSUE THREAD

**Issue by Ye83** [collabora/WhisperLive#193]
How can I replace the model on Hugging Face? Could you please give me specific guidance? I've been puzzled by this for several days.

**Comment by Ye83** [comment]
![image](https://github.com/collabora/WhisperLive/assets/17722346/3a86beec-7cbf-4849-af4d-43e648f84d36)
I want to use this model from HuggingFace, but it doesn't have a model.bin file. Does that mean it can't be replaced?

**Comment by makaveli10** [comment]
@Ye83 you should follow [model conversion guide in the faster_whisper readme](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#model-conversion) and once you have your custom model converted to faster_whisper format i.e. ctranslate you should be able to start the server with you custom faster_whisper model as follows:
```
python3 run_server.py --port 9090 \
                      --backend faster_whisper
                      -fw "/path/to/custom/faster/whisper/model"
```

**Comment by Ye83** [comment]
@makaveli10 I appreciate your response

**Comment by Ye83** [comment]
The issue has been resolved.
