### ISSUE TITLE
Integrating with Hugging Face pretrained models

### ISSUE THREAD

**Issue by mkatic007** [collabora/WhisperLive#197]
Could you please explain how to add a Hugging Face pretrained model to work with WhisperLive?

**Comment by makaveli10** [comment]
@mkatic007 that is indeed possible with both backends i.e. `tensorrt` as well as `faster_whisper`
- TensorRT
[This guide](https://github.com/makaveli10/TensorRT-LLM/tree/cuda12.2/examples/whisper) converts the original whisper models to TensorRT. Adjust accoridingly to convert huggingface pretrained `whisper` models.

- faster_whisper
[Faster whisper has a section in their readme](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#model-conversion) which shows how you can convert hf model to ctranslate2. Once you have the model converted run the server with your custom model:
```
python3 run_server.py --port 9090 \
                      --backend faster_whisper
                      -fw "/path/to/custom/faster/whisper/model"
```
