### ISSUE TITLE
GPU mode consumes half of available CPUs

### ISSUE THREAD

**Issue by zucher** [collabora/WhisperLive#201]
on the version 0.4.1, CPU transcription consume less cpu than GPU +CPU.

with:
docker run -it -p 9090:9090 ghcr.io/collabora/whisperlive-cpu:latest

![image](https://github.com/collabora/WhisperLive/assets/3034596/4e719839-2845-4045-bc85-6043a8917717)

With GPU:
docker run -it --gpus all -p 9090:9090 ghcr.io/collabora/whisperlive-gpu:latest

![image](https://github.com/collabora/WhisperLive/assets/3034596/7bd66920-0eaf-4bf6-b7a4-854bef393b93)

![image](https://github.com/collabora/WhisperLive/assets/3034596/143e98b4-0ff9-494d-a694-93bf05e4845e)

The called model was french / small
So I don't understand why ? And with such results why still using GPU ;-)

so seriously seems threads not sleeping correctly during GPU processing.

**Comment by Asma-droid** [comment]
I have the same issue
