### ISSUE TITLE
'Backend' error in command prompt

### ISSUE THREAD

**Issue by Farooq87** [collabora/WhisperLive#209]
c:\>python run_server.py --port 9090 --backend faster_whisper
Traceback (most recent call last):
  File "c:\run_server.py", line 31, in <module>
    server.run(
TypeError: TranscriptionServer.run() got an unexpected keyword argument 'backend'

Any solutions?

**Comment by makaveli10** [comment]
@Farooq87 That shouldn't happen if you are on the latest version. Can you try upgrading whisper-live and test if it resolves the issue. Because, I see that we have a `backend` command-line arg in run_server.py:
https://github.com/collabora/WhisperLive/blob/a9683319e05bb881f560b713260d0727edf69cae/run_server.py#L34

**Comment by Farooq87** [comment]
> @Farooq87 That shouldn't happen if you are on the latest version. Can you try upgrading whisper-live and test if it resolves the issue. Because, I see that we have a `backend` command-line arg in run_server.py:
> 
> https://github.com/collabora/WhisperLive/blob/a9683319e05bb881f560b713260d0727edf69cae/run_server.py#L34

I updated Faster Whisper, but still have the same error
![11111](https://github.com/collabora/WhisperLive/assets/80591773/badfaab0-a47e-46dc-8583-7b8882dfc00a)

**Comment by makaveli10** [comment]
@Farooq87 Instead of `faster-whisper`, you need to check that you run latest version of `whisper-live`.
```
pip install --upgrade whisper-live
```

**Comment by makaveli10** [comment]
@Farooq87 just tested with latest version of `whisper-live`:
```
$ python run_server.py --port 9090 --backend faster_whisper
INFO:websockets.server:connection open
INFO:root:New client connected
INFO:root:Running faster_whisper backend.
INFO:faster_whisper:Processing audio with duration 00:01.024
INFO:faster_whisper:VAD filter removed 00:00.000 of audio
.
.
```
