### ISSUE TITLE
Word-level timestamps

### ISSUE THREAD

**Issue by stenlan** [collabora/WhisperLive#211]
Hello,

First of all, thank you a lot for this library. I wonder; is it possible to obtain word-level timestamps from this model like it is from WhisperX, whisper-timestamped, faster-whisper or the openAI api itself?

**Comment by stenlan** [comment]
I've actually implemented this myself now on https://github.com/stenlan/WhisperLive-ts, would there be any interest in adding this as a toggleable option?

**Comment by makaveli10** [comment]
@stenlan yes please, one thing i would test if it has performance implications i.e. slows down the real-time perf.
