### ISSUE TITLE
Whisper version selection for Docker deployment

### ISSUE THREAD

**Issue by ruifengma** [collabora/WhisperLive#213]
Can I select the speficied Whisper version to deploy on the tensorRT docker?

**Comment by makaveli10** [comment]
@ruifengma Can you please elaborate, by version do you mean the version of `whisper` literally or the `model_size` for e.g. `tiny`, `base`, `large-v3`?

**Comment by makaveli10** [comment]
@ruifengma not sure if this helps but you can change to a specific whisper model size here
https://github.com/collabora/WhisperLive/blob/main/TensorRT_whisper.md#whisper-tensorrt-engine
