### ISSUE TITLE
duration threshold to start transcription?

### ISSUE THREAD

**Issue by bryanhpchiang** [collabora/WhisperLive#22]
great repo. thanks for making this

![image](https://github.com/collabora/whisper-live/assets/98059440/5aa43eeb-0bd6-4a7a-a69b-cc4cb9fae2f3)

one issue i'm running into is that short utterances don't get transcribed immediately because the duration is too short (by default its set to 1s in server.py). 

but if the duration is decreased then accuracy is also degraded. any suggestions for fixing this?

**Comment by makaveli10** [comment]
@bryanhpchiang Yes, this is something we saw as well. Eventually after some testing `1s` is what gave us the best results. Feel free to test out on your end and open a PR if you get better results.
