### ISSUE TITLE
[WARN]: Unable to access microphone. [Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by harsha-kvs** [collabora/WhisperLive#235]
Running the client on the localhost always hits this issues, Server Message says "Message from Server: TensorRT-LLM not supported on Server yet. Reverting to available backend: 'faster_whisper'"
But the server is working and running

**Comment by harsha-kvs** [comment]
I fixed that by installing voice control using 
sudo apt-get install pavucontrol

**Comment by Json0926** [comment]
> I fixed that by installing voice control using sudo apt-get install pavucontrol

can not fix
