### ISSUE TITLE
Maybe a way to avoid hallucinations

### ISSUE THREAD

**Issue by Hlizzzzz** [collabora/WhisperLive#246]
I kept encountering hallucinations when I tried transcribe from microphone, if "lang=en" it will be "Thank you" , if "lang=zh" it will be something like"字幕by索兰娅" "字幕由 Amara.org 社群提供", I think it is a problem due to bad training data, the model I used is large-v3.
Then I found a solution on whisper project:

![1719891170650](https://github.com/collabora/WhisperLive/assets/107842280/af5bdd29-eafd-4909-9cac-f89d25f9568c)

But I don't know in this project where should I change or add this argument

**Comment by asr-lord** [comment]
On this line in transcriber.py https://github.com/collabora/WhisperLive/blob/main/whisper_live/transcriber.py#L213 you've `--suppress_tokens` parameter.

**Comment by kstan79** [comment]
ya i have same issue with faster-whisper, during I use microphone record speech, when no voice it will always return same text "字幕by索兰娅"

**Comment by andreclerigo** [comment]
I am currently using this client.py, and I still get this issue


```
from whisper_live.rasa_client import TranscriptionClient

# Instantiate the client
client = TranscriptionClient(
    host="localhost",
    port=9090,
    lang="en",
    translate=False,
    model="turbo",
    use_vad=False,
    save_output_recording=True,
    output_recording_filename="./output_recording.wav",
    output_transcription_path="./output.srt",
)

client()
```

**Comment by FeverKing** [comment]
The issue is still there.
