### ISSUE TITLE
vad.py crashes after recent change to silero-vad

### ISSUE THREAD

**Issue by nimrod-gileadi** [collabora/WhisperLive#254]
When using WhisperLive with VAD, I saw this crash:

```
ERROR:root:Unexpected error: Required inputs (['state']) are missing from input feed (['input', 'h', 'c', 'sr']).
INFO:root:Cleaning up.
INFO:root:Exiting speech to text thread
```

Looks like recently, silero-vad uploaded a new silero_vad.onnx file which changes the expected inputs (in this commit https://github.com/snakers4/silero-vad/commit/fd1f1a62b75ec5824993aa4062b55c0965b9621b)

A quick fix for me was to edit this line in [vad.py](https://github.com/collabora/WhisperLive/blob/cf721e8b5337066154b7d47bf89bd7df9f2318cd/whisper_live/vad.py#L97) to point at `https://github.com/snakers4/silero-vad/raw/a9d2b591dea11451d23aa4b480eff8e55dbd9d99/files/silero_vad.onnx`, the previous version of the file.

**Comment by makaveli10** [comment]
Closed by https://github.com/collabora/WhisperLive/pull/247
