### ISSUE TITLE
Required inputs (['state']) are missing from input feed

### ISSUE THREAD

**Issue by nullonesix** [collabora/WhisperLive#255]
when running the default [tensorRT server](https://github.com/collabora/WhisperLive/blob/main/TensorRT_whisper.md) and making a client query, i get the following error:

> [07/08/2024-07:19:09] Unexpected error: Required inputs (['state']) are missing from input feed (['input', 'h', 'c', 'sr']).

my client looks like:

```py
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "199.204.135.78",
  9091,
  lang="en",
  translate=False,
#   model="small",
#   use_vad=False,
#   save_output_recording=True,                         # Only used for microphone input, False by Default
#   output_recording_filename="./output_recording.wav"  # Only used for microphone input
)
client()
```

**Comment by nullonesix** [comment]
and then if i try to use the default faster whisper i get:

> INFO:root:Single model mode currently only works with custom models.
> INFO:websockets.server:connection open
> INFO:root:New client connected
> ERROR:root:Error during new connection initialization: 'model'

**Comment by asr-lord** [comment]
You have to change VAD downloand link: https://github.com/collabora/WhisperLive/issues/249#issuecomment-2207857559

**Comment by nullonesix** [comment]
> You have to change VAD downloand link in vad.py: [#249 (comment)](https://github.com/collabora/WhisperLive/issues/249#issuecomment-2207857559)
> 
> ```
> #Actual
> def download(model_url="https://github.com/snakers4/silero-vad/raw/master/files/silero_vad.onnx"):
> #New
> def download(model_url="https://github.com/snakers4/silero-vad/raw/v4.0/files/silero_vad.onnx"):
> ```

i tried this and i get the same error

**Comment by nullonesix** [comment]
just install vim and modify the link, mb i forgot i was in a docker container

**Comment by makaveli10** [comment]
Closed by https://github.com/collabora/WhisperLive/pull/247
