### ISSUE TITLE
TensorRT backend gives no output

### ISSUE THREAD

**Issue by jasonngap1** [collabora/WhisperLive#261]
Hi, I have built a TensoRT engine and tried running the command:
```
python3 run_server.py -p 9090 -b tensorrt -trt {path_to_engine}
```
but the only output that I have received is the below:
```
INFO:root:Custom model option was provided. Switching to single model mode.
```
Is there something that I am doing wrong? I built the model using the repo here: https://github.com/k2-fsa/sherpa/tree/master/triton/whisper

**Comment by hexdrx** [comment]
And so what? Nothing changes 😕 
Still Same output. With original model and with custom
