### ISSUE TITLE
error during new connection initialization: 'model'

### ISSUE THREAD

**Issue by prasadchandrasekaran** [collabora/WhisperLive#265]
I'm running the CPU version of Whisper Live, and here's the client code I'm using:

from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "localhost",
  9090,
  lang="en",
  translate=False  # Only used for microphone input
)
client()

However, I'm encountering a connection failure with the following error:

**Client Error:**
python3 client.py
[INFO]: * recording
[INFO]: Waiting for server ready ...
False en transcribe
[INFO]: Opened connection
[INFO]: Websocket connection closed: 1000:

**Server Error:**
INFO:root:Single model mode currently only works with custom models.
INFO:websockets.server:connection open
INFO:root:New client connected
ERROR:root:Error during new connection initialization: 'model'

**Comment by makaveli10** [comment]
Closed due to inactivity. Feel free to re-open if needed.
