### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by Mar2ck** [collabora/WhisperLive#27]
When the server tries to process the first 30 seconds of input from the browser I get this error:
```
INFO:faster_whisper:Processing audio with duration 00:30.000
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/media/UltraStorageBTRFS/Programs/Linux/anaconda3/envs/whisper-live/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/media/UltraStorageBTRFS/Programs/Linux/anaconda3/envs/whisper-live/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marc/Documents/GitClones/whisper-live/server.py", line 152, in speech_to_text
    self.language, lang_prob = self.transcriber.transcribe(
ValueError: too many values to unpack (expected 2)
```

The issue is with line 152, even though it has two variables to unpack to it's throwing an error. I fixed it by doing this but there's probably a better way. Line 152 onwards:
```python
transcriber_output = self.transcriber.transcribe(
    input_bytes, 
    initial_prompt=None,
    language=self.language,
    task=self.task
)
self.language = transcriber_output[0]
lang_prob = transcriber_output[1]
```

**Comment by makaveli10** [comment]
@Mar2ck to reproduce at my end:
- which extension did you use chrome/firefox? 
- And what are the options you selected in the extension popup?

**Comment by Mar2ck** [comment]
It's the chrome extension and it happens with the default settings:
![Default Settings](https://github.com/collabora/WhisperLive/assets/6759254/1f03056f-18ba-4851-b7b0-ca05d42df472)
I found that if I enable multilingual model, change the two drop downs to something and uncheck multilingual again then the error no longer happens:
![Fix Settings](https://github.com/collabora/WhisperLive/assets/6759254/a9c430ce-f56c-4001-82f1-8035fd4518d6)

**Comment by makaveli10** [comment]
@Mar2ck this should close this issue. Feel free to test out the PR on your end and let us know if the issue still persists.
https://github.com/collabora/WhisperLive/pull/28

**Comment by Mar2ck** [comment]
Yep that fixes it thanks 👍
