### ISSUE TITLE
Failed to launch server

### ISSUE THREAD

**Issue by Nrgte** [collabora/WhisperLive#281]
When I try to launch the server it fails with the following error message:
Thanks for your help!

(venv) F:\Projects\WhisperLive>run_server.py --port 9090 --backend faster_whisper

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "F:\Projects\WhisperLive\run_server.py", line 40, in <module>
    from whisper_live.server import TranscriptionServer
  File "F:\Projects\WhisperLive\whisper_live\server.py", line 14, in <module>
    from whisper_live.vad import VoiceActivityDetector
  File "F:\Projects\WhisperLive\whisper_live\vad.py", line 7, in <module>
    import onnxruntime
  File "F:\Projects\WhisperLive\venv\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "F:\Projects\WhisperLive\venv\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an exception set
INFO:root:Single model mode currently only works with custom models.

**Comment by Don-Chad** [comment]
Hi Guys, 

It's seems impossible to install numpty since it's so old (2014 I see). Does not want to find the wheel, etc. Is this still possible on windows?
