### ISSUE TITLE
Is SSL Required for Frontend Functionality?

### ISSUE THREAD

**Issue by mnwato** [collabora/WhisperLive#286]
I have successfully deployed the backend, but the frontend developer is unable to work with it. He mentioned that the browser does not allow microphone access without SSL. Is SSL necessary for frontend functionality?

**Comment by makaveli10** [comment]
Right now no, we dont have that integrated. Something we want to look into and should be quick to integrate as well. Feel free to open a PR if you have something working with SSL.
