### ISSUE TITLE
Scaling server and adding load balancers or adding clusters

### ISSUE THREAD

**Issue by INF800** [collabora/WhisperLive#29]
Hi,

I tested for single client on Tesla T4 and the transcriptions are real-time. But what is the best way to scale server code to 50-100 concurrent users at least (more preferred but I mentioned 50-100 concurrent users because it will need 3 k8 pods with tesla t4 each)?

**Comment by zoq** [comment]
@INF800 the best way to serve 100+ concurrent users is to add batching to the pipeline, we did some initial experiments and based on the numbers we have seen, it would be possible to pack that many concurrent users on a few machines.

The model supports batching already, but the backend around it needs an update.

**Comment by timmolter** [comment]
Hi @INF800 Did you ever set up load balancing in production? How is it going?

**Comment by INF800** [comment]
Hey @timmolter, I've followed this architecture. so far so good. Currently not working on the project though.

https://open-speech-ekstep.github.io/asr_streaming_service/

**Comment by joaogabrieljunq** [comment]
> Hey @timmolter, I've followed this architecture. So far so good. Currently not working on the project though.
> 
> https://open-speech-ekstep.github.io/asr_streaming_service/

Any progress on this? I would like to know the results. I am trying to build a multi-client transcription server with batch inference.

**Comment by makaveli10** [comment]
@joaogabrieljunq this is something we are not looking into at the moment but feel free to work on batching and open a PR.

thanks

**Comment by orgh0** [comment]
>the best way to serve 100+ concurrent users is to add batching to the pipeline, we did some initial experiments and based on the numbers we have seen, it would be possible to pack that many concurrent users on a few machines.
The model supports batching already, but the backend around it needs an update.

@zoq  - could you share more details of these experiments and the math behind it? I'm trying to make an estimate of how many GPUs i'd need to scale to 1000+ concurrent users
