### ISSUE TITLE
Open AI/Azure API integration

### ISSUE THREAD

**Issue by pratikiitdh** [collabora/WhisperLive#290]
I want to build a realtime speech to speech conversation and ended up here. Is it possible to use this project with open ai whisper API? Or any other way to achieve real time speech to speech conversation. Any help is appreciated

**Comment by Gldkslfmsd** [comment]
hi, we tried it, but: https://github.com/ufal/whisper_streaming/issues/94

**Comment by makaveli10** [comment]
@pratikiitdh there is [WhisperFusion](https://github.com/collabora/WhisperFusion) that might be interesting for you.
