### ISSUE TITLE
Using Models Straight from Hugging Face

### ISSUE THREAD

**Issue by BasselAshi** [collabora/WhisperLive#294]
I've seen Issue #197 but I am wondering if we can directly pass the hugging face model name and let faster whisper download it for us instead of using the downloaded path. It looks like Faster Whisper [already supports this](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#load-a-converted-model).

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/298
