### ISSUE TITLE
Incompatibility with whisper-live 0.5.1 and faster-whisper 1.0.1 > merge_segments

### ISSUE THREAD

**Issue by Kirchlive** [collabora/WhisperLive#312]
Hi collabora,

I encountered an issue while trying to use `whisper-live 0.5.1` with the specified dependency `faster-whisper==1.0.1`.
Problem: The server fails to start because the merge_segments function from faster-whisper.vad cannot be found.

Error message as follows:
`Traceback (most recent call last):
  File "C:\Pro\WhisperLive-main\run_server.py", line 40, in <module>
    from whisper_live.server import TranscriptionServer
  File "C:\Pro\WhisperLive-main\whisper_live\server.py", line 15, in <module>
    from whisper_live.transcriber import WhisperModel
  File "C:\Pro\WhisperLive-main\whisper_live\transcriber.py", line 25, in <module>
    from faster_whisper.vad import (
ImportError: cannot import name 'merge_segments' from 'faster_whisper.vad' (C:\Pro\WhisperLive-main\venv\Lib\site-packages\faster_whisper\vad.py)`

Background:
According to setup.py, whisper-live 0.5.1 requires faster-whisper==1.0.1.
However, the merge_segments function in `faster_whisper.vad` seems to have changed in version 1.0.1.
As a result, the current implementation of whisper-live appears incompatible with faster-whisper 1.0.1.

Steps to Reproduce:
Create a fresh `venv` virtual environment.

Install dependencies:
`pip install setup.py`

Due to error:
`pip install numpy==1.24.4`
`pip install onnxruntime==1.16.0`

Start the server:
`python run_server.py --port 9090 --backend faster_whisper`

Expected Behavior: The server should start without errors.
Actual Behavior: The import of merge_segments fails, preventing the server from starting.

Suggestions:
Please review the changes in faster-whisper 1.0.1 and update the code accordingly.
If merge_segments is no longer required, consider removing or replacing it with an alternative function.
Alternatively, fix the dependency to faster-whisper==1.0.0 until the issue is resolved.
Additional Information:

OS: Windows 10
Python Version: 3.11
Installed Versions:
whisper-live==0.5.1
faster-whisper==1.0.1

Thank you for your work on this project! Looking forward.

**Comment by pi0neerpat** [comment]
Upgrading to `faster-whisper==1.1.0` fixed this for me
