### ISSUE TITLE
Bug? File Transcription never completes. 

### ISSUE THREAD

**Issue by justinlevi** [collabora/WhisperLive#41]
Using the JFK wave file here: https://github.com/ggerganov/whisper.cpp/blob/master/samples/jfk.wav

Here is my `run_client.py`
```
from whisper_live.client import TranscriptionClient
client = TranscriptionClient("0.0.0.0", "8080", is_multilingual=False, lang="en", translate=False)
client("./jfk.wav")
```

running the client only transcribes the following: 

And so, my fellow America, ask not what your country can do
for you.

<img width="951" alt="image" src="https://github.com/collabora/WhisperLive/assets/1117989/90d72577-4b76-49e5-a72c-c40c2331f967">

**Comment by makaveli10** [comment]
Reproduced on my end. Let me know if [https://github.com/collabora/WhisperLive/pull/43] doesnt fix the issue

**Comment by justinlevi** [comment]
Unfortunately that didn't seem to fix the problem. See attached screen recording. 

Getting a few more tokens back, but not the full transcript

```
And so, my fellow America, ask not what your country can do
for you, as...
```

https://github.com/collabora/WhisperLive/assets/1117989/76071277-4de1-4638-a82b-5671968fd2ba

**Comment by makaveli10** [comment]
I dont see this on my end when using a `GPU`, over the `CPU` yes.

I think your server is not able to compute fast enough to be real-time. Its something that the client needs to take care of i.e. wait sometime before closing the websocket connection so that it receives everything. If I run the server on the `cpu` I see the same issue.

After your audio ends, I have added a simple wait for 15 seconds before closing the websocket to consume the server responses. Feel free to change 15 to 20 if its still not showing the complete response.

**Comment by justinlevi** [comment]
Hmm, seems that there are still some cleanup and timeout issues when running on cpu. Quite often I'll get the following error output from the server

ERROR:root:[ERROR]: 'WhisperModel' object has no attribute 'model'
^CTraceback (most recent call last):
  File "/Users/justinwinter/projects/whisperlive/./run_server.py", line 5, in <module>
    server.run("0.0.0.0")
  File "/Users/justinwinter/projects/whisperlive/whisper_live/server.py", line 136, in run
    server.serve_forever()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/whisper_live/lib/python3.9/site-packages/websockets/sync/server.py", line 226, in serve_forever
    poller.select()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/whisper_live/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

**Comment by justinlevi** [comment]
If I add the following to the client  `play_file`: method before the stream is closed, I can get the transcription to work every time now

```
            elapsed = time.time() - self.LAST_RESPONSE_RECIEVED
            while elapsed < self.DISCONNECT_IF_NO_RESPONSE_FOR:
                continue
```

**Comment by makaveli10** [comment]
@justinlevi I did that in [this commit](https://github.com/collabora/WhisperLive/pull/43/commits/82a1aa449d40e0af066f3bb5fcbb14a885cfa70e). So, we can merge this now?

**Comment by justinlevi** [comment]
Otherwise the stream is closed right when the file is done playing which we don't want if we're waiting for the server to send back transcription text

**Comment by makaveli10** [comment]
In that case, could you test if checking the `elapsed_time` once in `play_file` solves the issue. Wondering if we really need to check again in `close_websocket`?

**Comment by justinlevi** [comment]
Yeah, I don't think we need it in close_websocket.
