### ISSUE TITLE
Client Gets Stuck

### ISSUE THREAD

**Issue by Sajid-Hameed63** [collabora/WhisperLive#47]
Hi everyone,

I am working on the WhisperLive to get the transcriptions on client side. It is working now, **but there is an issue. The issue is that after a few minutes (1 or 2 minutes), it does not print the updated (new) transcription for the audio on the terminal. It feels like that it gets stuck.** 

Can anyone help me in the issue mentioned above? Thanks in advance.

**Comment by makaveli10** [comment]
@Sajid-Hameed63 can you share code snippet to reproduce the issue? In addition to that, if you could share the logs as well that would be great.

**Comment by Sajid-Hameed63** [comment]
Yes, I am sharing the server.py & client.py module located in whisper_live folder. Please check these files. When I run a long audio for testing, it gets stuck somewhere and does not print text. Zip file for code is given below:

[code.zip](https://github.com/collabora/WhisperLive/files/12673022/code.zip)

**Comment by Sajid-Hameed63** [comment]
My issue is resolved. Now it is not stuck at any stage. Actually, I was setting the frame_offset equal to a very low value. Thanks everyone
