### ISSUE TITLE
can`t start server in windows

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [collabora/WhisperLive#57]
here is the log after this code 
` from whisper_live.server import TranscriptionServer`
` server = TranscriptionServer()`
` server.run("0.0.0.0", 9090)`

> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "D:\Code\whisper\WhisperLive-0.0.7\main.py", line 2, in <module>
>     server = TranscriptionServer()
>   File "D:\Code\whisper\WhisperLive-0.0.7\whisper_live\server.py", line 38, in __init__
>     self.vad_model = VoiceActivityDetection()
>   File "D:\Code\whisper\WhisperLive-0.0.7\whisper_live\vad.py", line 21, in __init__
>     self.session = onnxruntime.InferenceSession(path, providers=['CPUExecutionProvider'], sess_options=opts)
>   File "C:\Users\25813\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "C:\Users\25813\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from C:\Users\25813/.cache/whisper-live/silero_vad.onnx failed:C:\a\_work\1\s\onnxruntime\core\graph\model.cc:134 onnxruntime::Model::Model ModelProto does not have a graph.

i have installed requirement from **client.txt** and **server.txt**,and i can not installed them from setup.sh,cause i am running server and client both in the same windwos system,as well as setup.py ,it error `Perhaps my account does not have write access to this directory`

and i don`t installed cuda,is this error linked with this or something else?
Lokk forward for your early reply

**Comment by systemoutprintlnhelloworld** [comment]
![image](https://github.com/collabora/WhisperLive/assets/62531937/ea0d0832-fe2c-4262-9836-b1a1b34083fa)
it`s an empty file

**Comment by makaveli10** [comment]
can you try changing the download path here https://github.com/collabora/WhisperLive/blob/410b91d1339058bf9de4f29b54c39f66be7698c5/whisper_live/vad.py#L98
and see if that works

**Comment by systemoutprintlnhelloworld** [comment]
thanks for your reply! 
it`s a network problem
i just download it manually and put it in the right place

**Comment by systemoutprintlnhelloworld** [comment]
here is another question:
why i open a video in broswer and click this extension to record after the server is runing in locahost:9090,the extension's console runs error like
 `
 The message port closed before a response was received
`
or
`
 Cannot access contents of the page. Extension manifest must request permission to access the respective host.
`
like this picture
![image](https://github.com/collabora/WhisperLive/assets/62531937/25309e6c-5c67-4721-b32c-0abd8462dedd)
i try to run the extension in chrome either
but error as same as edge
by the way,the network column is empty so their is no request between B and S

could u please tell me how to fix it,or is their anything i ignore to present?

**Comment by rpurinton** [comment]
FYI the reason this doesn't work on windows is  subprocess.run(["wget", "-O"
