### ISSUE TITLE
Transcribing a HLS stream?

### ISSUE THREAD

**Issue by vannman** [collabora/WhisperLive#62]
I've tried transcribing an HLS stream by inputing a link to a .m3u8 file, but it does not seem to work. Is that feature supported somehow?

**Comment by makaveli10** [comment]
@vannman I dont think we support that yet. We support transcribing a file, microphone and in the browser with our chrome/firefox extension plugin.

**Comment by AffiTheCreator** [comment]
It is possible I managed to do it you need to write your script that will read the stream from an FFmpeg process and create the numpy array. its the ame things as the mic. 

I don't have the code in this machine but send me a message and I can explain you better.

**Comment by jhormigo** [comment]
I've submitted a PR for an implementation for the HLS stream transcription @vannman. It's awaiting merge.

cc: @makaveli10
