### ISSUE TITLE
The `setup.sh` file is using `CRLF`, which should be `LF` since it's a shell script.

### ISSUE THREAD

**Issue by orrest** [collabora/WhisperLive#65]
The problem occurs when build the docker image.

**Comment by zoq** [comment]
You are on Windows or Linux? [setup.sh](https://github.com/collabora/WhisperLive/blob/main/setup.sh) is already `LF`.

**Comment by zdaar** [comment]
I had the same issue on windows trying to build the container. I used dos2unix to patch setup.sh and it was able to docker build

**Comment by Stinosko** [comment]
I also had the same issue, used visual studio to switch the file from `CRLF` to `LF`.

**Comment by makaveli10** [comment]
@Stinosko what OS are you on? I double checked the file format and it is `LF` indeed

**Comment by Stinosko** [comment]
@makaveli10 It was on Ubuntu 22.04 LTS in Windows subsystem for Linux

**Comment by Stinosko** [comment]
My theory so far:
I first git cloned the repo in windows to start an docker instance with the docker files. I had some issue so i copied the files into WSL as that was faster than git clone the repo again. Maybe by trying to run the repo in windows the file got changed into `CRLF` 🤷‍♂️
