### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by KangByungwoo** [collabora/WhisperLive#67]
When I installed and ran it, nothing happened and got the below error message. Could you help resolve this issue? Thanks!
![image](https://github.com/collabora/WhisperLive/assets/26239966/fec091bb-8971-4ff2-962c-bc5f067b9495)

**Comment by makaveli10** [comment]
@KangByungwoo what is your chrome version?

**Comment by kingwpf** [comment]
> @KangByungwoo what is your chrome version?

Same issue for me,
Version: 120.0.6099.129(arm64)
OS: MacOS 14.2.1

**Comment by timmolter** [comment]
Same here. Latest Chrome Version on latest version io MacOS. Here's a screenshot of the console:

<img width="829" alt="Screenshot 2024-01-11 at 2 34 52 PM" src="https://github.com/collabora/WhisperLive/assets/738972/74d0b82d-00e9-45eb-a8fd-241424061e54">

**Comment by timmolter** [comment]
For Firefox, I get this for connecting to localhost and/or `Use Collabora Server`: <img width="1012" alt="Screenshot 2024-01-11 at 2 44 12 PM" src="https://github.com/collabora/WhisperLive/assets/738972/a2e4f0b3-5526-4260-a452-3d1dea2a759c">

**Comment by makaveli10** [comment]
@timmolter @kingwpf Thanks for raising the issue. We are looking into this.

**Comment by makaveli10** [comment]
I had to restart the Collabora Server and it works, Our server is just for testing purposes. We recommend that you use your own servers. We have limits to the number of clients that can connect and also there is a timeout of 10 minutes for each client. So, kindly setup your servers.

**Comment by timmolter** [comment]
@makaveli10 Thanks for the help.

I still get the same failed results, for both testing against the Collabora Server and locally running WhisperLive on localhost.

In Chrome I get the no audio error and in Firefox I get the could not establish connection.

<img width="1338" alt="Screenshot 2024-01-12 at 10 56 24 AM" src="https://github.com/collabora/WhisperLive/assets/738972/62c55f7f-ff68-40f7-b445-139bdedb39ab">

MacOS 14.2.1

**Comment by timmolter** [comment]
OK, I just made some progress on Chrome. I didn't realize there had to be audio running in the tab! Digging into the source code gave me a clue. It now works with the Collabora server on Chrome.

However, using local WhisperLive I get: `Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by timmolter** [comment]
@makaveli10 OK, let me try. In the mean time, I could confirm that Firefox also works with Collabora server when I first make sure that some audio is playing in the tab. Somehow I thought that the extension used the microphone. Whoops!

**Comment by timmolter** [comment]
OK, it's all working now. I set the port to 9090 in both extensions.

**Comment by timmolter** [comment]
Do you have a simple script available that uses the websocket interface and taps into the microphone? Something that we can see at a lower level the up and down streaming rates?

**Comment by makaveli10** [comment]
@timmolter no, we dont have a script for that. Not sure I understand! What exactly do you want to see ?

**Comment by timmolter** [comment]
Basically, I'm looking for a bash script or even Python that connects over the websocket interface and streams from the system microphone.

**Comment by timmolter** [comment]
Something like advertised here: https://alphacephei.com/vosk/server

`Testing with microphone`

https://github.com/alphacep/vosk-server/blob/master/websocket/test.py

**Comment by makaveli10** [comment]
@timmolter No we dont have atest script but I think you can set it up with the client and server.
