### ISSUE TITLE
Is it possible to add transcribed text to a file in real time?

### ISSUE THREAD

**Issue by MargaShilo** [collabora/WhisperLive#71]

**Comment by makaveli10** [comment]
With the python client? Yes. The server sends a list of last 10 segments to the client which has the timestamps for each segment. [That can be used](https://github.com/collabora/WhisperLive/blob/da86c182051fdbb882020e5338a7ec6c0e65b94a/whisper_live/client.py#L168) in python client to write the transcriptions in the required format to a file.

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/121 adds transcript to SRT file.
