### ISSUE TITLE
How to set the specified local model?

### ISSUE THREAD

**Issue by sujianwei1** [collabora/WhisperLive#77]
How to set the specified local model?I want to use the large model

**Comment by makaveli10** [comment]
Do you have a finetuned model? Or you want to set up a local server?

**Comment by kundanashish** [comment]
Hi @makaveli10 
I have a fine-tuned distill-whisper model. I have also converted it using ct2-transformers-converter. Pls guide how to use that local mode.

**Comment by zoq** [comment]
The easiest solution would be to set the path of the converted model here - https://github.com/collabora/WhisperLive/blob/7b2f5cff721af30dd20ccea06337188e0c47f726/whisper_live/server.py#L228
