### ISSUE TITLE
Modell size and modell change

### ISSUE THREAD

**Issue by tatarmb4s** [collabora/WhisperLive#78]
Hi!
Thank you for this great project!

How can we switch the whisper model, to the latest whisperV3, and how can we use the large-v3 model?

Also, If I have a fine-tuned large-v3 model, how can I use the custom model?

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/82

**Comment by makaveli10** [comment]
Refer to [faster whisper to convert your custom model](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#model-conversion) to `ctranslate2` and then it should work in WhisperLive as well
