### ISSUE TITLE
Unexpected keyword argument 'model_size'

### ISSUE THREAD

**Issue by asadal** [collabora/WhisperLive#79]
I ran the server.py on my Mac and was successful.
I then ran the client.py and got the following error:

```
# Run the client
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
  "localhost",
  9090,
  is_multilingual=True,
  lang="ko",
  translate=False,
  model_size="base"
)
client()
```

```
Traceback (most recent call last):
  File "/Users/asadal/Documents/Dev/Hani/WhisperLive_streamlit.py", line 5, in <module>
    client = TranscriptionClient(
TypeError: TranscriptionClient.__init__() got an unexpected keyword argument 'model_size'
```

How do I fix this?

==============

Plus:
Is there a way to save the text output by the chrome extension to a file?

Thanks,

**Comment by makaveli10** [comment]
@asadal what version of whisper-live are you using ?
No, for now we dont support saving the text output in chrome extension to a file. That being said, you can manually edit the extension and save the outputs from the server to a text file here https://github.com/collabora/WhisperLive/blob/db2e0bbcdd73a6e6ba7c788e3fcaae550a91caca/Audio-Transcription-Chrome/content.js#L188

Just write the segments to a file as soon as any new segments are received.

**Comment by lightwastak3n** [comment]
@makaveli10 
The param is called model not model_size https://github.com/collabora/WhisperLive/blob/3498787ccdab781d319634a00154c8fb80b46f27/whisper_live/client.py#L521
I guess it got renamed at some point.
I made a PR.

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/121 should resolve the `model_size` argument issue
