### ISSUE TITLE
Is `bufferSize` required to be `4096` sample frames?

### ISSUE THREAD

**Issue by hcljsq** [collabora/WhisperLive#84]
I want to know if bufferSize is required to be a fixed value. Thank you. ❤️ 

https://github.com/collabora/WhisperLive/blob/e30286c046ca6d8c7a9eac42da59f7fd97514fc0/Audio-Transcription-Chrome/options.js#L159C39-L159C39

**Comment by makaveli10** [comment]
@hcljsq you can change it to what works best for you `4096` with a sample rate of `16000` gives `256 ms` of audio in one chunk. I think you want to have a dynamic chunk size?

**Comment by hcljsq** [comment]
I originally didn't understand what the role of `bufferSize` was here. But your explanation made me understand. Thank you!

The audio length of `256` milliseconds is derived from the calculation based on the sample rate of `16000` and the number of data points, which is `4096`. This is determined by the formula:

<img width="495" alt="image" src="https://github.com/collabora/WhisperLive/assets/30150098/eff8e502-d1a3-4a35-bf86-6384623f611b">

In this case, <img width="211" alt="image" src="https://github.com/collabora/WhisperLive/assets/30150098/c7f5f472-ec9b-4160-937e-5a6ab1d1f021"> ms.
