### ISSUE TITLE
Set `initial_prompt` and `vad_parameters` from the client.

### ISSUE THREAD

**Issue by hcljsq** [collabora/WhisperLive#85]
I have gone through [server.py](https://github.com/collabora/WhisperLive/blob/e30286c046ca6d8c7a9eac42da59f7fd97514fc0/whisper_live/server.py#L353-L360) and noticed that the `initial_prompt` and `vad_parameters` are hardcoded. Is there a way to make them configurable by the client? Perhaps set them in the first message after establishing a WebSocket connection? Alternatively, could you provide some guidance so that I could submit a PR?

**Comment by hcljsq** [comment]
And also `max_clients`.

**Comment by makaveli10** [comment]
Good point. Feel free to submit a PR; you can send those params from the client side in the first message as you mentioned while establishing the first connection with server.

**Comment by hcljsq** [comment]
I will submit a PR. Thank you for your guidance. ❤️
