### ISSUE TITLE
String Representation and Precision Control for Start and End Outputs

### ISSUE THREAD

**Issue by hcljsq** [collabora/WhisperLive#87]
I suggest setting the output of start and end as strings, and controlling them to three decimal places, which is accurate to millimeters.

Current outputs:

```json
{
  "start": 29.304000000000002,
  "end": 30.624000000000002,
  "text": "OK"
}
```

Suggested:

```json
{
  "start": "29.304"
  "end": "30.624",
  "text": "OK"
}
```

**Comment by zoq** [comment]
Good point, actually, I had an issue in the past with OBS, that required the suggested precision. Do you want me to open a PR with a fix or do you want to open a PR; don't feel obligated, just like to make sure we don't do duplicated work.

**Comment by hcljsq** [comment]
Sure, I'd like to give it a try. I'll submit a PR tomorrow. ❤️

**Comment by zoq** [comment]
Great, let us know if you run into any issues.
