### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by tmceld** [collabora/WhisperLive#97]
I feel a little foolish here, as i am probably missing something obvious.

I get that the client has the onMessage function - but i am struggling to see where i can access this to either save to a file or to pass to another function?

Also, while i am here - do any flags need to be passed to use GPU?  output feels a little sluggish, for having a 3090.

**Comment by makaveli10** [comment]
@tmceld we probably lack documentation around how you can write the outputs to a file. Bear with us, we have that in the pipeline to make it more obvious how to do it.
For now, you are right about onmessage, you can pass the segments [here](https://github.com/collabora/WhisperLive/blob/a7eedc5d84d8926e5a4db18c6605ffc89947d58b/whisper_live/client.py#L175) to another function and write them to a file. One thing to note the last segment in this list can change in the next result you receive from the server.

**Comment by makaveli10** [comment]
@tmceld we ourselves use 3090 for whiser-live and it can run medium in real time. Are you still having issues with it?
I would check if the gpu is being utilised at all.

**Comment by tmceld** [comment]
thank you @makaveli10 I will do, i moved on to work on another part of my workflow, but i will go back and look at this soon.

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/pull/121 should close this.
