### ISSUE TITLE
Program goes into a loop

### ISSUE THREAD

**Issue by ecybron** [collabora/WhisperLive#99]
Hi, 
_I apologize if this question seems basic. I am new to this field and would appreciate your guidance._ 

I have completed all the tasks but I don't know how to start the [server](https://github.com/collabora/WhisperLive?tab=readme-ov-file#transcribe-audio-from-browser). Could you please provide instructions on how to get the local server up and running? Do we need to modify anything in client.py or server.py?

The program hangs when I run run_server.py from the root directory. If I force stop the program, it outputs the message displayed in the screenshot. 

<img width="917" alt="boo" src="https://github.com/collabora/WhisperLive/assets/154909722/4e2c5832-a2ce-4011-a091-360df2d7ea30">

**Comment by makaveli10** [comment]
@ecybron can you uncomment [logging verbosity line](https://github.com/collabora/WhisperLive/blob/0c01d7b1e510900410337b85f2c95cc9bd94fc06/whisper_live/server.py#L9) and see if this logs anything useful?

**Comment by ecybron** [comment]
> @ecybron can you uncomment [logging verbosity line](https://github.com/collabora/WhisperLive/blob/0c01d7b1e510900410337b85f2c95cc9bd94fc06/whisper_live/server.py#L9) and see if this logs anything useful?

Unfortunately, nothing has changed (

**Comment by makaveli10** [comment]
Maybe you can build docker image on your mac and start the server in docker?

**Comment by timmolter** [comment]
@ecybron I installed Docker Desktop from <https://docs.docker.com/desktop/install/mac-install/>, and the ran `docker run -it -p 9090:9090 whisper-live:latest`. That's all you need to do IIRC.

**Comment by makaveli10** [comment]
@ecybron did the docker setup work for you?
